# Generated by Django 5.1.1 on 2024-11-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('-start_datetime',), 'permissions': [('can_deactivate_mailing', 'can deactivate mailing'), ('can_watch_mailing', 'can watch mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ('-last_attempt', 'status'), 'permissions': [('can_watch_attempts', 'can watch attempts')], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылок'},
        ),
    ]
