# Generated by Django 5.1.1 on 2024-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_is_published_alter_article_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="опубликовано"),
        ),
    ]
